CREATE TABLE `appabout` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) DEFAULT NULL COMMENT '頁面標題，可選',
  `sections_json` JSON NOT NULL COMMENT 'cutSections 序列化 JSON',
  `status` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '1=啟用,0=停用',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;